server:
  port: 8888
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          #配置github
          uri: https://github.com/xy20001114/day8.git
          #配置搜索目录
          search-paths:
            - configfiles
      #配置分支
      label: dev


