#服务名称，按服务名称去配置中心找对应配置文件
spring:
  application:
    name: config
  resources:
    static-locations: file:D:\\pic\\
  cloud:
    config:
      #配置中心的地址
      uri: http://localhost:8888
      #指定拉去的dev环境，它与spring.application.name属性才能从Git仓库找到配置文件
      profile: dev
      #可以指定拉去配置的Git分支
      label: master

